# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.api.limit_order_api import LimitOrderApi  # noqa: E501
from openocean_api.rest import ApiException


class TestLimitOrderApi(unittest.TestCase):
    """LimitOrderApi unit test stubs"""

    def setUp(self):
        self.api = openocean_api.api.limit_order_api.LimitOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controller_limit_order_create(self):
        """Test case for controller_limit_order_create

        list by address   # noqa: E501
        """
        pass

    def test_controller_limit_order_update(self):
        """Test case for controller_limit_order_update

        list all   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
