# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.api.swap_api import SwapApi  # noqa: E501
from openocean_api.rest import ApiException


class TestSwapApi(unittest.TestCase):
    """SwapApi unit test stubs"""

    def setUp(self):
        self.api = openocean_api.api.swap_api.SwapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controller_swap_dex_list(self):
        """Test case for controller_swap_dex_list

        dexList   # noqa: E501
        """
        pass

    def test_controller_swap_get_transaction(self):
        """Test case for controller_swap_get_transaction

        getTransaction   # noqa: E501
        """
        pass

    def test_controller_swap_quote(self):
        """Test case for controller_swap_quote

        quote   # noqa: E501
        """
        pass

    def test_controller_swap_swap_quote(self):
        """Test case for controller_swap_swap_quote

        swap_quote   # noqa: E501
        """
        pass

    def test_controller_swap_token_list(self):
        """Test case for controller_swap_token_list

        tokenList   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
