# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.api.nft_api import NftApi  # noqa: E501
from openocean_api.rest import ApiException


class TestNftApi(unittest.TestCase):
    """NftApi unit test stubs"""

    def setUp(self):
        self.api = openocean_api.api.nft_api.NftApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controller_nft_assets(self):
        """Test case for controller_nft_assets

        Create Listing   # noqa: E501
        """
        pass

    def test_controller_nft_buy(self):
        """Test case for controller_nft_buy

        Submit Order   # noqa: E501
        """
        pass

    def test_controller_nft_check_order(self):
        """Test case for controller_nft_check_order

        Create Offer   # noqa: E501
        """
        pass

    def test_controller_nft_collections(self):
        """Test case for controller_nft_collections

        Buy   # noqa: E501
        """
        pass

    def test_controller_nft_detail(self):
        """Test case for controller_nft_detail

        NFT Detail   # noqa: E501
        """
        pass

    def test_controller_nft_get_delta_and_curve_type(self):
        """Test case for controller_nft_get_delta_and_curve_type

        Collections   # noqa: E501
        """
        pass

    def test_controller_nft_get_orders(self):
        """Test case for controller_nft_get_orders

        Listings   # noqa: E501
        """
        pass

    def test_controller_nft_import_asset(self):
        """Test case for controller_nft_import_asset

        Order Status   # noqa: E501
        """
        pass

    def test_controller_nft_offer(self):
        """Test case for controller_nft_offer

        Swap Token   # noqa: E501
        """
        pass

    def test_controller_nft_orders(self):
        """Test case for controller_nft_orders

        NFT Orders   # noqa: E501
        """
        pass

    def test_controller_nft_quote(self):
        """Test case for controller_nft_quote

        User Activity   # noqa: E501
        """
        pass

    def test_controller_nft_rankings(self):
        """Test case for controller_nft_rankings

        Rankings   # noqa: E501
        """
        pass

    def test_controller_nft_report(self):
        """Test case for controller_nft_report

        NFTs   # noqa: E501
        """
        pass

    def test_controller_nft_sell(self):
        """Test case for controller_nft_sell

        Quote Token   # noqa: E501
        """
        pass

    def test_controller_nft_sign(self):
        """Test case for controller_nft_sign

        Cancel   # noqa: E501
        """
        pass

    def test_controller_nft_swap(self):
        """Test case for controller_nft_swap

        Collection Activity   # noqa: E501
        """
        pass

    def test_controller_nft_testscan(self):
        """Test case for controller_nft_testscan

        Offers   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
