# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.models.activity_by_address_response import ActivityByAddressResponse  # noqa: E501
from openocean_api.rest import ApiException


class TestActivityByAddressResponse(unittest.TestCase):
    """ActivityByAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityByAddressResponse(self):
        """Test ActivityByAddressResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_api.models.activity_by_address_response.ActivityByAddressResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
