# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.models.get_balace_request import GetBalaceRequest  # noqa: E501
from openocean_api.rest import ApiException


class TestGetBalaceRequest(unittest.TestCase):
    """GetBalaceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalaceRequest(self):
        """Test GetBalaceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_api.models.get_balace_request.GetBalaceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
