# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.models.cancel_response import CancelResponse  # noqa: E501
from openocean_api.rest import ApiException


class TestCancelResponse(unittest.TestCase):
    """CancelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelResponse(self):
        """Test CancelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_api.models.cancel_response.CancelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
