# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openocean_api
from openocean_api.models.sell_item import SellItem  # noqa: E501
from openocean_api.rest import ApiException


class TestSellItem(unittest.TestCase):
    """SellItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSellItem(self):
        """Test SellItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_api.models.sell_item.SellItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
