# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class BuyTransactionData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_from': 'str',
        'to': 'str',
        'data': 'str',
        'value': 'str',
        'approve': 'list[ApproveItem]'
    }

    attribute_map = {
        '_from': 'from',
        'to': 'to',
        'data': 'data',
        'value': 'value',
        'approve': 'approve'
    }

    def __init__(self, _from=None, to=None, data=None, value=None, approve=None, _configuration=None):  # noqa: E501
        """BuyTransactionData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self.__from = None
        self._to = None
        self._data = None
        self._value = None
        self._approve = None
        self.discriminator = None

        self._from = _from
        self.to = to
        self.data = data
        self.value = value
        if approve is not None:
            self.approve = approve

    @property
    def _from(self):
        """Gets the _from of this BuyTransactionData.  # noqa: E501

        from address  # noqa: E501

        :return: The _from of this BuyTransactionData.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this BuyTransactionData.

        from address  # noqa: E501

        :param _from: The _from of this BuyTransactionData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and _from is None:
            raise ValueError("Invalid value for `_from`, must not be `None`")  # noqa: E501

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this BuyTransactionData.  # noqa: E501

        to address  # noqa: E501

        :return: The to of this BuyTransactionData.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this BuyTransactionData.

        to address  # noqa: E501

        :param to: The to of this BuyTransactionData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    @property
    def data(self):
        """Gets the data of this BuyTransactionData.  # noqa: E501

        transaction data  # noqa: E501

        :return: The data of this BuyTransactionData.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this BuyTransactionData.

        transaction data  # noqa: E501

        :param data: The data of this BuyTransactionData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def value(self):
        """Gets the value of this BuyTransactionData.  # noqa: E501

        value  # noqa: E501

        :return: The value of this BuyTransactionData.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this BuyTransactionData.

        value  # noqa: E501

        :param value: The value of this BuyTransactionData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def approve(self):
        """Gets the approve of this BuyTransactionData.  # noqa: E501

        approve list  # noqa: E501

        :return: The approve of this BuyTransactionData.  # noqa: E501
        :rtype: list[ApproveItem]
        """
        return self._approve

    @approve.setter
    def approve(self, approve):
        """Sets the approve of this BuyTransactionData.

        approve list  # noqa: E501

        :param approve: The approve of this BuyTransactionData.  # noqa: E501
        :type: list[ApproveItem]
        """

        self._approve = approve

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BuyTransactionData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuyTransactionData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BuyTransactionData):
            return True

        return self.to_dict() != other.to_dict()
