# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class MinSendRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_chain_id': 'float',
        'to_chain_id': 'float',
        'address': 'str'
    }

    attribute_map = {
        'from_chain_id': 'fromChainId',
        'to_chain_id': 'toChainId',
        'address': 'address'
    }

    def __init__(self, from_chain_id=None, to_chain_id=None, address=None, _configuration=None):  # noqa: E501
        """MinSendRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._from_chain_id = None
        self._to_chain_id = None
        self._address = None
        self.discriminator = None

        self.from_chain_id = from_chain_id
        self.to_chain_id = to_chain_id
        self.address = address

    @property
    def from_chain_id(self):
        """Gets the from_chain_id of this MinSendRequest.  # noqa: E501

        chain id  # noqa: E501

        :return: The from_chain_id of this MinSendRequest.  # noqa: E501
        :rtype: float
        """
        return self._from_chain_id

    @from_chain_id.setter
    def from_chain_id(self, from_chain_id):
        """Sets the from_chain_id of this MinSendRequest.

        chain id  # noqa: E501

        :param from_chain_id: The from_chain_id of this MinSendRequest.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and from_chain_id is None:
            raise ValueError("Invalid value for `from_chain_id`, must not be `None`")  # noqa: E501

        self._from_chain_id = from_chain_id

    @property
    def to_chain_id(self):
        """Gets the to_chain_id of this MinSendRequest.  # noqa: E501

        chain id  # noqa: E501

        :return: The to_chain_id of this MinSendRequest.  # noqa: E501
        :rtype: float
        """
        return self._to_chain_id

    @to_chain_id.setter
    def to_chain_id(self, to_chain_id):
        """Sets the to_chain_id of this MinSendRequest.

        chain id  # noqa: E501

        :param to_chain_id: The to_chain_id of this MinSendRequest.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and to_chain_id is None:
            raise ValueError("Invalid value for `to_chain_id`, must not be `None`")  # noqa: E501

        self._to_chain_id = to_chain_id

    @property
    def address(self):
        """Gets the address of this MinSendRequest.  # noqa: E501

        token address  # noqa: E501

        :return: The address of this MinSendRequest.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this MinSendRequest.

        token address  # noqa: E501

        :param address: The address of this MinSendRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MinSendRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MinSendRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MinSendRequest):
            return True

        return self.to_dict() != other.to_dict()
