# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class OrderFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'market': 'str',
        'search_attributes': 'str'
    }

    attribute_map = {
        'address': 'address',
        'market': 'market',
        'search_attributes': 'searchAttributes'
    }

    def __init__(self, address=None, market=None, search_attributes=None, _configuration=None):  # noqa: E501
        """OrderFilter - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._address = None
        self._market = None
        self._search_attributes = None
        self.discriminator = None

        self.address = address
        if market is not None:
            self.market = market
        if search_attributes is not None:
            self.search_attributes = search_attributes

    @property
    def address(self):
        """Gets the address of this OrderFilter.  # noqa: E501

        rankings reponse id(address or slug)  # noqa: E501

        :return: The address of this OrderFilter.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this OrderFilter.

        rankings reponse id(address or slug)  # noqa: E501

        :param address: The address of this OrderFilter.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def market(self):
        """Gets the market of this OrderFilter.  # noqa: E501

        market  # noqa: E501

        :return: The market of this OrderFilter.  # noqa: E501
        :rtype: str
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this OrderFilter.

        market  # noqa: E501

        :param market: The market of this OrderFilter.  # noqa: E501
        :type: str
        """
        allowed_values = ["opensea", "lookrare", "x2y2", "sudoswap"]  # noqa: E501
        if (self._configuration.client_side_validation and
                market not in allowed_values):
            raise ValueError(
                "Invalid value for `market` ({0}), must be one of {1}"  # noqa: E501
                .format(market, allowed_values)
            )

        self._market = market

    @property
    def search_attributes(self):
        """Gets the search_attributes of this OrderFilter.  # noqa: E501

        attributes map  # noqa: E501

        :return: The search_attributes of this OrderFilter.  # noqa: E501
        :rtype: str
        """
        return self._search_attributes

    @search_attributes.setter
    def search_attributes(self, search_attributes):
        """Sets the search_attributes of this OrderFilter.

        attributes map  # noqa: E501

        :param search_attributes: The search_attributes of this OrderFilter.  # noqa: E501
        :type: str
        """

        self._search_attributes = search_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderFilter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderFilter):
            return True

        return self.to_dict() != other.to_dict()
