# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class OrderData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offerer': 'str',
        'start_time': 'str',
        'end_time': 'str'
    }

    attribute_map = {
        'offerer': 'offerer',
        'start_time': 'startTime',
        'end_time': 'endTime'
    }

    def __init__(self, offerer=None, start_time=None, end_time=None, _configuration=None):  # noqa: E501
        """OrderData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._offerer = None
        self._start_time = None
        self._end_time = None
        self.discriminator = None

        self.offerer = offerer
        self.start_time = start_time
        self.end_time = end_time

    @property
    def offerer(self):
        """Gets the offerer of this OrderData.  # noqa: E501

        offerer  # noqa: E501

        :return: The offerer of this OrderData.  # noqa: E501
        :rtype: str
        """
        return self._offerer

    @offerer.setter
    def offerer(self, offerer):
        """Sets the offerer of this OrderData.

        offerer  # noqa: E501

        :param offerer: The offerer of this OrderData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and offerer is None:
            raise ValueError("Invalid value for `offerer`, must not be `None`")  # noqa: E501

        self._offerer = offerer

    @property
    def start_time(self):
        """Gets the start_time of this OrderData.  # noqa: E501

        startTime  # noqa: E501

        :return: The start_time of this OrderData.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this OrderData.

        startTime  # noqa: E501

        :param start_time: The start_time of this OrderData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this OrderData.  # noqa: E501

        endTime  # noqa: E501

        :return: The end_time of this OrderData.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this OrderData.

        endTime  # noqa: E501

        :param end_time: The end_time of this OrderData.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderData):
            return True

        return self.to_dict() != other.to_dict()
