# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class PaymentAssetItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'symbol': 'str',
        'is_native': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'symbol': 'symbol',
        'is_native': 'isNative'
    }

    def __init__(self, id=None, symbol=None, is_native=None, _configuration=None):  # noqa: E501
        """PaymentAssetItem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._symbol = None
        self._is_native = None
        self.discriminator = None

        self.id = id
        self.symbol = symbol
        self.is_native = is_native

    @property
    def id(self):
        """Gets the id of this PaymentAssetItem.  # noqa: E501

        id  # noqa: E501

        :return: The id of this PaymentAssetItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PaymentAssetItem.

        id  # noqa: E501

        :param id: The id of this PaymentAssetItem.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def symbol(self):
        """Gets the symbol of this PaymentAssetItem.  # noqa: E501

          # noqa: E501

        :return: The symbol of this PaymentAssetItem.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this PaymentAssetItem.

          # noqa: E501

        :param symbol: The symbol of this PaymentAssetItem.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and symbol is None:
            raise ValueError("Invalid value for `symbol`, must not be `None`")  # noqa: E501

        self._symbol = symbol

    @property
    def is_native(self):
        """Gets the is_native of this PaymentAssetItem.  # noqa: E501

        is native  # noqa: E501

        :return: The is_native of this PaymentAssetItem.  # noqa: E501
        :rtype: bool
        """
        return self._is_native

    @is_native.setter
    def is_native(self, is_native):
        """Sets the is_native of this PaymentAssetItem.

        is native  # noqa: E501

        :param is_native: The is_native of this PaymentAssetItem.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and is_native is None:
            raise ValueError("Invalid value for `is_native`, must not be `None`")  # noqa: E501

        self._is_native = is_native

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentAssetItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentAssetItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PaymentAssetItem):
            return True

        return self.to_dict() != other.to_dict()
