# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openocean_api.configuration import Configuration


class SellRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sender': 'str',
        'market': 'str',
        'sell': 'list[SellItem]'
    }

    attribute_map = {
        'sender': 'sender',
        'market': 'market',
        'sell': 'sell'
    }

    def __init__(self, sender=None, market=None, sell=None, _configuration=None):  # noqa: E501
        """SellRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._sender = None
        self._market = None
        self._sell = None
        self.discriminator = None

        self.sender = sender
        self.market = market
        self.sell = sell

    @property
    def sender(self):
        """Gets the sender of this SellRequest.  # noqa: E501

        seller  # noqa: E501

        :return: The sender of this SellRequest.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this SellRequest.

        seller  # noqa: E501

        :param sender: The sender of this SellRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and sender is None:
            raise ValueError("Invalid value for `sender`, must not be `None`")  # noqa: E501

        self._sender = sender

    @property
    def market(self):
        """Gets the market of this SellRequest.  # noqa: E501

        market  # noqa: E501

        :return: The market of this SellRequest.  # noqa: E501
        :rtype: str
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this SellRequest.

        market  # noqa: E501

        :param market: The market of this SellRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and market is None:
            raise ValueError("Invalid value for `market`, must not be `None`")  # noqa: E501
        allowed_values = ["opensea", "lookrare", "x2y2"]  # noqa: E501
        if (self._configuration.client_side_validation and
                market not in allowed_values):
            raise ValueError(
                "Invalid value for `market` ({0}), must be one of {1}"  # noqa: E501
                .format(market, allowed_values)
            )

        self._market = market

    @property
    def sell(self):
        """Gets the sell of this SellRequest.  # noqa: E501

        sell nft list  # noqa: E501

        :return: The sell of this SellRequest.  # noqa: E501
        :rtype: list[SellItem]
        """
        return self._sell

    @sell.setter
    def sell(self, sell):
        """Sets the sell of this SellRequest.

        sell nft list  # noqa: E501

        :param sell: The sell of this SellRequest.  # noqa: E501
        :type: list[SellItem]
        """
        if self._configuration.client_side_validation and sell is None:
            raise ValueError("Invalid value for `sell`, must not be `None`")  # noqa: E501

        self._sell = sell

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SellRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SellRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SellRequest):
            return True

        return self.to_dict() != other.to_dict()
